### ISSUE TITLE
default theme and accent not working

### ISSUE THREAD

**Issue by squera** [rmaguiar/hugo-theme-color-your-world#3]
Changing the flags `isDark` , `darkAccent`, and `lightAccent` does not seem to work.
Note: once some theme or some accent is manually selected, the manual selection works, but otherwise the default values are not set, the accents are all black and the theme is dark, which results in black on black.

**Comment by rmaguiar** [comment]
Right, I can see why the default accent colors didn't load. It was a mistake on my side, for some reason the `#` were removed from them at some point.

About changes not being applied, I wasn't able to reproduce that. Mind sharing the config?

**Comment by squera** [comment]
config-wise, here's what i tried:
OS: (1) MacOS Monterey 12.6 - Apple M1 e (2) Intel
Browser: (A) Safari Version 16.0 (17614.1.25.9.10, 17614),  (B) Firefox 111.0.1 (64-bit)

I tried (1) + (A) , (1) + (B) and (2) + (A)

I built the website with: hugo v0.101.0+extended darwin/arm64 BuildDate=unknown

are there more infos that can be useful?
I can't upload my `config.toml` so here it is:
```
baseURL = "https://squera.github.io"
languageCode = "en-us"
title = "Marco Patrignani"
theme = "color-your-world"

isDark = false

darkAccent   = "#1dbc91" 
lightAccent  = "#1f676b" 
presets = [ "#1f676b", "#f3a530", "#902b37", "#1dbc91", "#754e85", "#7fc121", "#a8314a", "#ff7433", "#3e6728", "#c063bd" ]




enableEmoji = true
enableInlineShortcodes = true

[params]
 logo = "/images/avatar-64.png"
 custom_css = "stylesheets/custom.css" 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
  	endLevel = 2
    ordered = false
    startLevel= 2
```

**Comment by squera** [comment]
indeed, that does the trick, thanks!
